
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------
package compiler;
/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int btoi_t = 52;
  public static final int open_parantheses_t = 20;
  public static final int bool_t = 31;
  public static final int remind_t = 7;
  public static final int dtoi_t = 50;
  public static final int if_t = 34;
  public static final int double_t = 30;
  public static final int class_t = 27;
  public static final int interface_t = 32;
  public static final int or_t = 15;
  public static final int Readline_t = 49;
  public static final int open_bracket_t = 24;
  public static final int open_close_brace_t = 26;
  public static final int protected_t = 55;
  public static final int itod_t = 51;
  public static final int for_t = 36;
  public static final int extends_t = 42;
  public static final int open_brace_t = 22;
  public static final int less_equal_t = 13;
  public static final int id_t = 58;
  public static final int multi_t = 5;
  public static final int new_t = 44;
  public static final int null_t = 40;
  public static final int great_equal_t = 11;
  public static final int string_t = 28;
  public static final int divide_t = 6;
  public static final int itob_t = 53;
  public static final int semi_colon_t = 19;
  public static final int array_t = 57;
  public static final int close_bracket_t = 25;
  public static final int public_t = 56;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int dot_t = 17;
  public static final int newArray_t = 45;
  public static final int double_literal_t = 62;
  public static final int colon_t = 18;
  public static final int not_equal_t = 9;
  public static final int Readinteger_t = 48;
  public static final int great_t = 10;
  public static final int while_t = 37;
  public static final int equal_t = 8;
  public static final int close_brace_t = 23;
  public static final int break_t = 38;
  public static final int string_literal_t = 60;
  public static final int implements_t = 43;
  public static final int plus_t = 3;
  public static final int int_t = 29;
  public static final int less_t = 12;
  public static final int int_literal_t = 61;
  public static final int assign_t = 4;
  public static final int not_t = 16;
  public static final int and_t = 14;
  public static final int void_t = 33;
  public static final int return_t = 39;
  public static final int minus_t = 2;
  public static final int else_t = 35;
  public static final int print_t = 46;
  public static final int boolean_literal_t = 59;
  public static final int continue_t = 47;
  public static final int private_t = 54;
  public static final int this_t = 41;
  public static final int close_parantheses_t = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "minus_t",
  "plus_t",
  "assign_t",
  "multi_t",
  "divide_t",
  "remind_t",
  "equal_t",
  "not_equal_t",
  "great_t",
  "great_equal_t",
  "less_t",
  "less_equal_t",
  "and_t",
  "or_t",
  "not_t",
  "dot_t",
  "colon_t",
  "semi_colon_t",
  "open_parantheses_t",
  "close_parantheses_t",
  "open_brace_t",
  "close_brace_t",
  "open_bracket_t",
  "close_bracket_t",
  "open_close_brace_t",
  "class_t",
  "string_t",
  "int_t",
  "double_t",
  "bool_t",
  "interface_t",
  "void_t",
  "if_t",
  "else_t",
  "for_t",
  "while_t",
  "break_t",
  "return_t",
  "null_t",
  "this_t",
  "extends_t",
  "implements_t",
  "new_t",
  "newArray_t",
  "print_t",
  "continue_t",
  "Readinteger_t",
  "Readline_t",
  "dtoi_t",
  "itod_t",
  "btoi_t",
  "itob_t",
  "private_t",
  "protected_t",
  "public_t",
  "array_t",
  "id_t",
  "boolean_literal_t",
  "string_literal_t",
  "int_literal_t",
  "double_literal_t"
  };
}

